# Generated by Django 3.1.3 on 2020-11-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(max_length=50)),
                ('dt_criacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLoja', models.CharField(max_length=128)),
                ('emailLoja', models.EmailField(max_length=254)),
                ('telefoneLoja', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=58)),
                ('precoProduto', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('codigoProduto', models.IntegerField(default='')),
                ('quantidadeEstoque', models.IntegerField(null=True)),
                ('corProduto', models.CharField(max_length=50, null=True)),
                ('tamanho', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('draft', 'Inativo')], max_length=15)),
                ('foto', models.ImageField(default='', upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=40)),
                ('fotoUsuario', models.ImageField(default='', upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codVendedor', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winx_sistema_loja.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winx_sistema_loja.categoria')),
                ('produtoAvaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winx_sistema_loja.produto')),
                ('usuarioTransacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winx_sistema_loja.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='vendedorCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winx_sistema_loja.vendedor'),
        ),
        migrations.CreateModel(
            name='loginAcessoS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, null=True)),
                ('senha', models.CharField(max_length=50)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winx_sistema_loja.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(max_length=240)),
                ('categoriaAvaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winx_sistema_loja.categoria')),
                ('produtoAvaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winx_sistema_loja.produto')),
            ],
        ),
    ]
