# Generated by Django 3.1.3 on 2020-11-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winx_sistema_loja', '0002_auto_20201120_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='corProduto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to=None),
        ),
    ]
