# Generated by Django 3.1.3 on 2020-11-21 03:10

from django.db import migrations, models
import winx_sistema_loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('winx_sistema_loja', '0003_auto_20201120_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='vendedorCod',
            field=models.IntegerField(blank=True, null=True, verbose_name=winx_sistema_loja.models.vendedor),
        ),
    ]
